services:
  - type: web
    name: momentum-pilot
    env: docker
    repo: https://github.com/jasonisdoing/momentum-pilot.git
    envVars:
      - key: MONGO_DB_CONNECTION_STRING
        # 중요: 실제 값은 Render 대시보드에서 Secret으로 설정하세요.
        # sync: false는 이 값이 YAML 파일과 동기화되지 않음을 의미합니다.
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: WEBAPP_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      # Dockerfile에서 EXPOSE한 포트와 일치해야 합니다.
      - key: PORT
        value: 10000
      # Streamlit이 외부 접속을 허용하도록 설정합니다.
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
