MARKET_REGIME_FILTER_ENABLED = True
MARKET_REGIME_FILTER_TICKER = "^GSPC"
MARKET_REGIME_FILTER_MA_PERIOD = 20

REALTIME_PRICE_ENABLED = True

MAX_PER_CATEGORY = 1
HOLDING_STOP_LOSS_PCT = 10  # 양수로 입력해도 자동으로 음수로 저장/해석됩니다.
